name: Ruff Linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          
      - name: Run Ruff
        run: |
          ruff check .
          
      # Optional: Add Ruff format checking
      - name: Run Ruff Format
        run: |
          ruff format . --check